[app]
name = "EMFight"
category = "Apps"
wifi_preference = false

[entry]
class = "EMFightApp"

[metadata]
author = "JonTheNiceGuy"
license = "Unlicense"
url = "https://github.com/JonTheNiceGuy/tildagon-emfight"
description = "BLE beacon scanner for EMFight game"
version = "0.0.1"
